export const domains = [
 {id:"software",name:"Software",unit:"accepted bug fixes",minutes:120,example:"Fix a reproducible bug, add regression tests, and pass maintainer review.",gate:"Working code, regression tests, security checks, maintainability, reviewer acceptance.",boundary:"A passing test alone does not establish a mergeable change.",capability:"Build · Debug · Verify",reference:"Qualified repository maintainer"},
 {id:"research",name:"Research",unit:"verified evidence briefs",minutes:180,example:"Answer a bounded question using traceable sources and an explicit uncertainty assessment.",gate:"Sources resolve, claims match evidence, contradictions addressed, independent review.",boundary:"A fluent draft is not a verified discovery.",capability:"Retrieve · Reason · Synthesize",reference:"Qualified subject researcher"},
 {id:"publishing",name:"Publishing",unit:"accepted book chapters",minutes:480,example:"Deliver an edited chapter against a fixed brief, research scope, and publication standard.",gate:"Editorial approval, factual checks, originality, citation and rights checks.",boundary:"Chapters do not automatically add up to a coherent, publishable book.",capability:"Create · Edit · Verify",reference:"Professional writer and declared editorial workflow"},
 {id:"support",name:"Customer support",unit:"resolved support cases",minutes:20,example:"Resolve a customer issue against policy with the correct action and a usable explanation.",gate:"Correct resolution, policy compliance, no harmful action, no reopening in the declared window.",boundary:"Fast replies are not successful resolutions.",capability:"Communicate · Act · Escalate",reference:"Trained support specialist"},
 {id:"finance",name:"Finance",unit:"reconciled account packs",minutes:180,example:"Reconcile a synthetic account ledger and document every discrepancy.",gate:"Arithmetic, source traceability, balanced totals, reviewer signoff.",boundary:"Research evaluation only. No trades, payments, or financial advice.",capability:"Calculate · Reconcile · Explain",reference:"Qualified accountant"},
 {id:"legal",name:"Legal operations",unit:"reviewed clause inventories",minutes:120,example:"Extract clauses from an authorized contract and flag differences against a fixed playbook.",gate:"Correct extraction, complete coverage, jurisdiction scope, qualified reviewer approval.",boundary:"No legal advice or autonomous legal decisions. Qualified review remains mandatory.",capability:"Retrieve · Compare · Flag",reference:"Qualified legal professional"},
 {id:"health",name:"Health administration",unit:"checked synthetic records",minutes:45,example:"Check a synthetic administrative record for missing fields and internal inconsistencies.",gate:"Completeness, privacy controls, correct administrative checks, qualified adjudication.",boundary:"No diagnosis, patient treatment, or clinical readiness claim.",capability:"Extract · Check · Escalate",reference:"Trained health administration specialist"},
 {id:"manufacturing",name:"Manufacturing",unit:"validated inspection reports",minutes:60,example:"Compare a synthetic inspection record with a fixed tolerance and maintenance specification.",gate:"Correct tolerance decisions, traceable measurements, escalation of unsafe cases.",boundary:"A simulation score does not certify a factory or physical robot.",capability:"Perceive · Compare · Verify",reference:"Qualified quality engineer"},
 {id:"logistics",name:"Logistics",unit:"feasible dispatch plans",minutes:90,example:"Produce a delivery plan under declared vehicle, capacity, time, and safety constraints.",gate:"Feasible constraints, explicit exceptions, audited cost calculation, operator approval.",boundary:"No live dispatch or vehicle control in this benchmark.",capability:"Plan · Optimize · Coordinate",reference:"Qualified dispatch planner"},
 {id:"education",name:"Education",unit:"reviewed learning packs",minutes:120,example:"Build a lesson, exercises, and answer key for a declared learning objective and audience.",gate:"Correct answers, pedagogical fit, accessibility, teacher review.",boundary:"Generated lessons are not evidence of improved student learning.",capability:"Explain · Create · Assess",reference:"Qualified teacher"},
 {id:"media",name:"Media production",unit:"approved media packages",minutes:240,example:"Create a scripted media package against a fixed brief with source and rights documentation.",gate:"Editorial accuracy, rights, accessibility, technical delivery, reviewer acceptance.",boundary:"Views and commercial impact require separate downstream measurement.",capability:"Create · Coordinate · Produce",reference:"Professional producer"},
 {id:"robotics",name:"Robotics",unit:"verified simulated missions",minutes:30,example:"Complete a navigation mission in a pinned simulator with obstacles and recovery conditions.",gate:"Goal reached, collision constraints, energy budget, reproducible state trace.",boundary:"Simulation and physical deployment scores must remain separate.",capability:"Perceive · Plan · Act",reference:"Qualified simulator operator"}
];

export const research = [
 {title:"Agent workdays are runtime",publisher:"OpenAI",date:"06 SEP 2026",url:"https://openai.com/index/research-acceleration-view-inside-openai/",text:"The 3.1 workday figure uses summed agent runtime and an eight hour day. It is not a human productivity multiplier.",design:"APx reports runtime separately from accepted output."},
 {title:"Human time measures task difficulty",publisher:"METR",date:"08 MAY 2026",url:"https://metr.org/time-horizons/",text:"Time horizons describe task difficulty at a stated success probability. They do not measure how long an agent ran or whether it can replace a job.",design:"Every APx score names a task family and reference cohort."},
 {title:"The clocks get harder with concurrency",publisher:"METR",date:"24 FEB 2026",url:"https://metr.org/blog/2026-02-24-uplift-update/",text:"A followup productivity study identified selection bias and unreliable task timing when developers ran concurrent agents.",design:"Keep wall time, agent runtime, and human labor distinct."},
 {title:"Grade professional deliverables",publisher:"OpenAI · GDPval",date:"25 SEP 2025",url:"https://openai.com/index/gdpval/",text:"GDPval evaluates work across 44 occupations using expert judging. Reported inference speed comparisons omit oversight and integration.",design:"Include review, repair, and integration before crediting output."},
 {title:"Work spans tools and applications",publisher:"Mercor · APEX Agents",date:"23 FEB 2026",url:"https://arxiv.org/abs/2601.14242",text:"APEX Agents provides 480 professional tasks with prompts, files, rubrics, and gold outputs.",design:"APx is a distinct measurement proposal, not Mercor’s APEX benchmark."},
 {title:"Use a task taxonomy, not job stereotypes",publisher:"O*NET Resource Center",date:"ACCESSED 07 SEP 2026",url:"https://www.onetcenter.org/content.html",text:"The occupational content model distinguishes tasks, work activities, context, skills, and abilities.",design:"Keep job, function, capability, and environment as separate tags."},
 {title:"Tests can miss real acceptance",publisher:"METR",date:"13 AUG 2025",url:"https://metr.org/blog/2025-08-12-research-update-towards-reconciling-slowdown-with-time-horizons/",text:"A small study found that passing functional tests did not imply a change was ready to merge. Results were specific to its older model and tasks.",design:"Require an independent acceptance gate beyond machine tests."},
 {title:"Protect evaluation integrity",publisher:"NIST",date:"AI RMF 1.0 · 2023",url:"https://www.nist.gov/itl/ai-risk-management-framework",text:"The voluntary AI risk framework supports contextual evaluation and trustworthiness across a system’s lifecycle.",design:"Safety failures block publishable scores. APx is not NIST certified."}
];
